### PR TITLE
Update isNativeToken flag

### PR DESCRIPTION
**Pull request by aminsato**
Update the  `isNativeToken` flag from `true` to `false`  for ticker are not native to the respective chain

### CODE REVIEW

**Comment by aminsato** [comment]
It ensures that non-native tokens are not displayed in the Choose Chains view.

**Comment by johnnyluo** [comment]
There are actually native token to pay for the gas

**Comment by aminsato** [comment]
> There are actually native token to pay for the gas

But some non-native tokens are also displayed in the VaultAccountsScreen view.The porpuse of my PR is to address to this issue.
image

**Comment by johnnyluo** [comment]
only WETH need to be set to IsNativeToken=false , ETH should be fine

**Pull request closed without merging**
